### PR TITLE
hotfix for zero_grad

### PR DESCRIPTION
**Pull request by TezRomacH**
## Description

- Fixed important bug for optimizers. Now it doesn't clear all model's parameters, but only if it owns them

## Related Issue

N/A

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the [Code of Conduct](https://github.com/catalyst-team/catalyst/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I have read the [Contributing](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md) guide.
- [x] I have checked the code-style using `make check-style`.
- [x] I have written the docstring in Google format for all the methods and classes that I used.
- [x] I have checked the docs using `make check-docs`.

### CODE REVIEW

**Review by bagxi — APPROVED** [review]

**Comment by Scitator** [comment]
@TezRomacH hi,
how this PR is going?

**Comment by TezRomacH** [comment]
for now I do not understand why the GAN CI is broken

it is worth waiting for updates on the implementation of the GANs and returning to this PR later

**Comment by Scitator** [comment]
:suumon: @asmekal @Arquestro check please

**Comment by Scitator** [comment]
is it deprecated? closing due to inactivity

**Comment by reyzharkov** [comment]
@Scitator it's not deprecated and it's still a bug according to this line https://github.com/catalyst-team/catalyst/blob/38a503c8af040906e377b7485d7fe15a7bc1de19/catalyst/core/callbacks/optimizer.py#L178

**Comment by reyzharkov** [comment]
@TezRomacH am I right that the only thing should be changed is `maybe_recursive_call(model, 'zero_grad')` -> `optimizer.zero_grad()` in appropriate line? why do we need something else?

**Comment by TezRomacH** [comment]
> @TezRomacH am I right that the only thing should be changed is maybe_recursive_call(model, 'zero_grad') -> optimizer.zero_grad() in appropriate line? why do we need something else?

yeap, the whole change is `optimizer.zero_grad()`

**Comment by reyzharkov** [comment]
@TezRomacH I think everything is OK, will you resolve conflicts so we can merge?

**Comment by Scitator** [comment]
merged during 20.03 update

**Pull request closed without merging**
