### PR TITLE
Fix bug when an exception is suppressed

### PR DESCRIPTION
**Pull request by ai-niki**
## Description

Happened if an exception had been raised before the exception-handlers were initialized

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have read the [Code of Conduct](https://github.com/catalyst-team/catalyst/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I have read the [Contributing](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md) guide.
- [ ] I have checked the code-style using `make check-style`.
- [ ] I have written the docstring in Google format for all the methods and classes that I used.
- [ ] I have checked the docs using `make check-docs`.

### CODE REVIEW

**Comment by Scitator** [comment]
@pokidyshev could you please merge with master? we have fixed the CI tests issue

**Comment by ai-niki** [comment]
@Scitator Any ideas on why Travis failed?

**Comment by Scitator** [comment]
I think we should update our ExceptionCallback rather then resolve this issue with additional if-else...
@TezRomacH could you please help with this Callback?

**Comment by ai-niki** [comment]
Note that this bug happens when `self.callbacks` and `self.loggers` are None. How updating ExceptionCallback could help?

**Comment by Scitator** [comment]
maybe, change exception handling logic here?
```
        except (Exception, KeyboardInterrupt) as ex:
            self.state.exception = ex
            self._run_event("exception", moment=None)
```
and raise it in such case?

**Comment by Scitator** [comment]
btw, for travis CI test fails – feel free to check it's output in `Checks` tab :)

**Comment by TezRomacH** [comment]
Build fell on Gan Example. It happens, I restarted it.

**Review by TezRomacH — APPROVED** [review]

**Comment by TezRomacH** [comment]
Now, it's okay :)

**Comment by TezRomacH** [comment]
@pokidyshev 

We discussed it with @scitator, and yes, it's better to take the `reraise` inside the `try-except`. It will be cheaper in terms of speed

https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/core/runner.py#L350

Could you please move the `reraise` to the runner's try-except? It is better to do it as soon as possible so that this important fix is included in version 19.12

**Comment by Scitator** [comment]
@TezRomacH could you please uncheck WIP when the PR would be ready?

**Comment by TezRomacH** [comment]
@pokidyshev how do you do? 🙂

**Comment by ai-niki** [comment]
@TezRomacH feel free to review :)

**Comment by Scitator** [comment]
@TezRomacH @bagxi  could you please add your review?

**Review by TezRomacH — APPROVED** [review]

**Pull request merged**
