### PR TITLE
Added NeptuneLogger and improved docstrings in SupervisedNeptuneRunner 

### PR DESCRIPTION
**Pull request by jakubczakon**
## Description

Wanted to make it easier for people to try Neptune runner and so I 
added an example where I use "ANONYMOUS" api token in a public projects.
By doing that users can easily try it out without registering, log things to neptune, and see
if they want to give it a try.

Now you can test it by running:

```python
runner.train(
    ...
    monitoring_params={
        "init": {
            "project_qualified_name": "shared/catalyst-integration",
            "api_token": "ANONYMOUS", 
        },
        "create_experiment": {
        ...
        }
    })
```

## Type of Change

- [x] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the [Code of Conduct](https://github.com/catalyst-team/catalyst/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I have read the [Contributing](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md) guide.
- [x] I have checked the code-style using `make check-codestyle`.
- [ ] I have written tests for all new methods and classes that I created.
- [x] I have written the docstring in Google format for all the methods and classes that I used.
- [ ] I have checked the docs using `make check-docs`.
- [ ] I have read I need to click 'Login as guest' to see Teamcity build logs.

### CODE REVIEW

**Comment by jakubczakon** [comment]
@Scitator the change is only in the docstring and I don't quite understand the failing tests.
What would you suggest I do?

**Comment by Scitator** [comment]
@jakubczakon Please, check the run logs, you have a "80+ characters line" issue :)
btw, don't you mind to contribute NeptuneLogger? All Runners would be removed in 20.04 release, as deprecated ones.

**Comment by jakubczakon** [comment]
@Scitator uuups sorry :)

Yeah sure I think it makes more sense as a `NeptuneLogger` -> will work on it and send it over. 
Would you prefer a separate PR or just change this one?

**Comment by Scitator** [comment]
@jakubczakon I think we could resolve Neptune integration here, in this PR only :)

**Comment by bagxi** [comment]
@jakubczakon could you please check the code style for your PR with `make codestyle`?

**Comment by jakubczakon** [comment]
I will @bagxi .
Also, I'll create NeptuneLogger later today.

**Comment by jakubczakon** [comment]
Hi @Scitator @bagxi,

It seems that I fixed those errors and locally `make codestyle` works:

```
(catalyst_dev) fancyname@fancyname-laptop-home:~/projects/catalyst$ make codestyle
pre-commit run
yapf.................................................(no files to check)Skipped
seed isort known_third_party.............................................Passed
isort................................................(no files to check)Skipped
Check Yaml...........................................(no files to check)Skipped
Trim Trailing Whitespace.............................(no files to check)Skipped
Flake8...............................................(no files to check)Skipped
```

But something fails when I submit it here. 
Errors seems fairly unrelated:

```
[14:30:47]Step 1/1: teamcity/py_codestyle.sh (Command Line) (1m:46s)
[14:30:50][Step 1/1] error: Could not remove config section 'remote.upstream'
[14:30:50][Step 1/1] + set -eo pipefail -v
[14:30:50][Step 1/1] 
[14:30:50][Step 1/1] pip install -r requirements/requirements.txt
[14:30:50][Step 1/1] + pip install -r requirements/requirements.txt
[14:31:35][Step 1/1] 
[14:31:35][Step 1/1] pip install -r requirements/requirements-cv.txt
[14:31:35][Step 1/1] + pip install -r requirements/requirements-cv.txt
[14:31:40][Step 1/1] 
[14:31:40][Step 1/1] pip install -r requirements/requirements-nlp.txt
[14:31:40][Step 1/1] + pip install -r requirements/requirements-nlp.txt
[14:31:48][Step 1/1] 
[14:31:48][Step 1/1] pip install -r requirements/requirements-rl.txt
[14:31:48][Step 1/1] + pip install -r requirements/requirements-rl.txt
[14:32:17][Step 1/1] 
[14:32:17][Step 1/1] pip install -r requirements/requirements-dev.txt
[14:32:17][Step 1/1] + pip install -r requirements/requirements-dev.txt
[14:32:31][Step 1/1] 
[14:32:31][Step 1/1] make check-codestyle
[14:32:31][Step 1/1] + make check-codestyle
[14:32:31][Step 1/1] 
[14:32:31][Step 1/1] 
[14:32:31][Step 1/1] # Parse -s flag which tells us that we should skip inplace
[14:32:31][Step 1/1] echo 'parse -s flag'
[14:32:31][Step 1/1] skip_inplace=""
[14:32:31][Step 1/1] while getopts ":s" flag; do
[14:32:31][Step 1/1]   case "${flag}" in
[14:32:31][Step 1/1]     s) skip_inplace="true" ;;
[14:32:31][Step 1/1]   esac
[14:32:31][Step 1/1] done
[14:32:31][Step 1/1] 
[14:32:31][Step 1/1] 
[14:32:31][Step 1/1] # test to make sure the code is isort compliant
[14:32:31][Step 1/1] echo 'isort: `isort -rc --check-only --settings-path ./setup.cfg`'
[14:32:31][Step 1/1] isort -rc --check-only --settings-path ./setup.cfg
[14:32:32][Step 1/1] make: *** [check-codestyle] Error 1
[14:32:33][Step 1/1] Process exited with code 2
[14:32:33][Step 1/1] Process exited with code 2 (Step: teamcity/py_codestyle.sh (Command Line))
[14:32:33][Step 1/1] Step teamcity/py_codestyle.sh (Command Line) failed
```

Can you help?

**Comment by jakubczakon** [comment]
Ok, I think it works now @Scitator @bagxi.

Also, I've added that `NeptuneLogger` to callbacks.

**Comment by jakubczakon** [comment]
It seems that it is fixed now @Scitator @bagxi just some build is hanging.

I've added that `NeptuneLogger` as well -> didn't drop `SupervisedNeptuneRunner` as I am expecting you to drop it in next versions of catalyst.

**Comment by Scitator** [comment]
@jakubczakon Thanks for PR!

**Pull request merged**
