### PR TITLE
Add WandbLogger

### PR DESCRIPTION
**Pull request by CrafterKolyan**
## Description

Add `WandbLogger`.

Tested it in some of my experiments. Found out there are a lot of `ResourceWarning`s in `wandb` library which were triggered after `warning.simplefilter("always")` in `catalyst/contrib/dl/runner/wandb.py`. All of these warnings are also reproducible using `catalyst.dl.SupervisedWandbRunner` in latest versions of `catalyst` (`>= 20.03`). Fixed most of warnings [here](https://github.com/wandb/client/pulls?q=is%3Apr+author%3ACrafterKolyan). Artifacts logging is still not done but basic functionality works.

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the [Code of Conduct](https://github.com/catalyst-team/catalyst/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I have read the [Contributing](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md) guide.
- [x] I have checked the code-style using `make check-codestyle`.
- [ ] I have written tests for all new methods and classes that I created.
- [x] I have written the docstring in Google format for all the methods and classes that I used.
- [ ] I have checked the docs using `make check-docs`.
- [x] I have read I need to click 'Login as guest' to see Teamcity build logs.

### CODE REVIEW

**Comment by Scitator** [comment]
Thanks for your contribution!

**Comment by ai-niki** [comment]
Adding `name` param to WandbLogger gives this error:

```
Traceback (most recent call last):
  File "/home/awecom/anaconda3/envs/workframe/bin/catalyst-dl", line 8, in <module>
    sys.exit(main())
  File "/home/awecom/anaconda3/envs/workframe/lib/python3.6/site-packages/catalyst/dl/__main__.py", line 41, in main
    COMMANDS[args.command].main(args, uargs)
  File "/home/awecom/anaconda3/envs/workframe/lib/python3.6/site-packages/catalyst/dl/scripts/run.py", line 117, in main
    distributed_run(args.distributed, main_worker, args, unknown_args)
  File "/home/awecom/anaconda3/envs/workframe/lib/python3.6/site-packages/catalyst/utils/distributed.py", line 192, in distributed_run
    worker_fn(*args, **kwargs)
  File "/home/awecom/anaconda3/envs/workframe/lib/python3.6/site-packages/catalyst/dl/scripts/run.py", line 112, in main_worker
    runner.run_experiment(experiment)
  File "/home/awecom/anaconda3/envs/workframe/lib/python3.6/site-packages/catalyst/core/runner.py", line 376, in run_experiment
    raise ex
  File "/home/awecom/anaconda3/envs/workframe/lib/python3.6/site-packages/catalyst/core/runner.py", line 361, in run_experiment
    self._run_stage(stage)
  File "/home/awecom/anaconda3/envs/workframe/lib/python3.6/site-packages/catalyst/core/runner.py", line 333, in _run_stage
    self._prepare_for_stage(stage)
  File "/home/awecom/anaconda3/envs/workframe/lib/python3.6/site-packages/catalyst/dl/core/runner.py", line 20, in _prepare_for_stage
    super()._prepare_for_stage(stage=stage)
  File "/home/awecom/anaconda3/envs/workframe/lib/python3.6/site-packages/catalyst/core/runner.py", line 224, in _prepare_for_stage
    callbacks = self._get_callbacks(stage)
  File "/home/awecom/anaconda3/envs/workframe/lib/python3.6/site-packages/catalyst/core/runner.py", line 191, in _get_callbacks
    callbacks = self.experiment.get_callbacks(stage)
  File "/home/awecom/anaconda3/envs/workframe/lib/python3.6/site-packages/catalyst/dl/experiment/config.py", line 526, in get_callbacks
    callback = self._get_callback(**callback_params)
  File "/home/awecom/anaconda3/envs/workframe/lib/python3.6/site-packages/catalyst/dl/experiment/config.py", line 512, in _get_callback
    callback = CALLBACKS.get_from_params(**params)
  File "/home/awecom/anaconda3/envs/workframe/lib/python3.6/site-packages/catalyst/utils/tools/registry.py", line 244, in get_from_params
    return self.get_instance(name, meta_factory=meta_factory, **kwargs)
TypeError: get_instance() got multiple values for argument 'name'
```

config:

```
    logger:
      callback: WandbLogger
      project: {{ project }}
      name: {{ name }}
```

**Comment by CrafterKolyan** [comment]
@pokidyshev Can you please provide code example how you use this config?
Because:
```
from catalyst import dl
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

class Projector(nn.Module):
    def __init__(self, input_size):
        super().__init__()
        self.linear = nn.Linear(input_size, 1)
    def forward(self, X):
        return self.linear(X).squeeze(-1)

X = torch.rand(16, 10)
y = torch.rand(X.shape[0])
model = Projector(X.shape[1])
dataset = TensorDataset(X, y)
loader = DataLoader(dataset, batch_size=8)
runner = dl.SupervisedRunner()

runner.train(
    model=model,
    loaders={
        "train": loader,
        "valid": loader
    },
    criterion=nn.MSELoss(),
    optimizer=optim.Adam(model.parameters()),
    logdir="log_example",
    callbacks=[
        dl.callbacks.WandbLogger(
            name="some name",
            project="some project"
        )
    ],
    num_epochs=10
)
```
works fine even though it has `name` attribute

**Comment by ai-niki** [comment]
This happens only in config mode cause this method has a `name` parameter and `kwargs` also: https://github.com/catalyst-team/catalyst/blob/8516b9d44546600ad597a1fffdf03b7eb23c5e98/catalyst/utils/tools/registry.py#L204

**Pull request merged**
