### PR TITLE
Add scale support for LRFinder

### PR DESCRIPTION
**Pull request by ivbelkin**

### CODE REVIEW

**Comment by Scitator** [comment]
Hi, thanks for contribution!

The only thing to do better is define something like `_calr_lr` during init to remove if-else usage every lr update. You can see an example of such approach in https://github.com/catalyst-team/catalyst/blob/master/catalyst/rl/agents/layers.py#L117

**Comment by ivbelkin** [comment]
Hi, thanks for fast review and hint!

**Comment by ivbelkin** [comment]
Have you any idea why there are two checks that seem identical? Did I something wrong?

**Comment by Scitator** [comment]
Checks are okay. Thanks!
There are only some Travis bugs, so nevermind.

**Pull request merged**
