### PR TITLE
add checkpoint name to trace

### PR DESCRIPTION
**Pull request by TezRomacH**
add checkpoint name to `catalyst-dl trace`
```
catalyst-dl trace cifar_simple -c stage1.0
```

or 
```
catalyst-dl trace cifar_simple --checkpoint=last --out-dir /path/to/output/
```

----

Tracing in `train` mode
```
catalyst-dl trace cifar_simple --checkpoint best --mode train
```

Tracing with grads
```
catalyst-dl trace cifar_simple --with-grad
```

### CODE REVIEW

**Comment by Scitator** [comment]
What do you think about an option of model tracing in train state / required-grad state?

**Comment by TezRomacH** [comment]
great idea, i'll add this!

**Comment by Scitator** [comment]
Could you please add an option to set model name by user?
something like
```bash
catalyst-dl trace cifar_simple --checkpoint best --mode train --with-grad --out-model=./my_traced_model.pth
```
Looks like it gives more flexibility for users

**Comment by TezRomacH** [comment]
ok

**Pull request merged**
