### PR TITLE
updated dl_cpu(workflows)- For passing CI-Tests

### PR DESCRIPTION
**Pull request by Atharva-Phatak**
## Before submitting (checklist)

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)?
- [ ] Did you check the code style? `catalyst-make-codestyle && catalyst-check-codestyle` (`pip install -U catalyst-codestyle`).
- [ ] Did you make sure to update the docs? We use Google format for all the methods and classes.
- [ ] Did you check the docs with `make check-docs`?
- [ ] Did you write any new necessary tests?
- [ ] Did you check that your code passes the unit tests `pytest .` ? 
- [ ] Did you add your new functionality to the docs?
- [ ] Did you update the [CHANGELOG](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md)?

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

PS
- [x] I know, that I could [join slack](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for pull request discussion.

## Note
Mentioned in comment of [#1131 ](https://github.com/catalyst-team/catalyst/pull/1131). so that CI test will run properly

### CODE REVIEW

**Comment by Scitator** [comment]
🤔  could you please try to update pandas requirement to `1.0.0`? the time has come 😂 
`requirements/requiremets-ml.txt` file

**Comment by Scitator** [comment]
we should find at least one extra minimal test to work with :)

**Comment by Atharva-Phatak** [comment]
> 🤔  could you please try to update pandas requirement to `1.0.0`? the time has come 😂 
> `requirements/requiremets-ml.txt` file

I agree. I wil make the necessary updates mentioned. 

While running tests I observed this, we run tests for ddp , gans and segmentation as well. On my laptop(single GPU) ddp failed , which was easy to debug, but wouldnt it be easier if run module specific tests while development and only test them. 
When created PR , other tests for ddp will run(which they do). 

I think this will make development and adding new modules easier. Just an opinion.  Will love to hear more. 🤔

**Comment by Scitator** [comment]
Not sure if I understand you correctly, cause:
- we have a bunch of DDP test under our `engines` folder here https://github.com/catalyst-team/catalyst/tree/master/catalyst/engines/tests
- there are also options to skip them if there are no GPUs available
- you always could use `pytest catalyst/engines` (or any other folder) to reduce the number of test cases you are interested in now
- during the CI, it's much better to run all the test cases :)

**Comment by Atharva-Phatak** [comment]
@Scitator updated requirments.txt

**Comment by Scitator** [comment]
Extra sys included, we will find the correct way for minimal requirements tests :joy:

**Comment by Atharva-Phatak** [comment]
> Extra sys included, we will find the correct way for minimal requirements tests joy

yes we will :joy:

**Comment by Scitator** [comment]
At least we have `dl-cpu (ubuntu-20.04, 3.6, minimal)` working already ;)

**Comment by Atharva-Phatak** [comment]
> At least we have `dl-cpu (ubuntu-20.04, 3.6, minimal)` working already ;)

Yes I am happy. We will soon have other versions working.

**Comment by Scitator** [comment]
Honestly speaking, not sure about that – GitHub has an interesting freezing bug here.
Could you please exclude:
```
- dl-cpu (ubuntu-18.04, 3.6, minimal)
- dl-cpu (ubuntu-18.04, 3.7, minimal)
- dl-cpu (ubuntu-18.04, 3.8, minimal)
- dl-cpu (ubuntu-20.04, 3.7, minimal)
- dl-cpu (ubuntu-20.04, 3.8, minimal)
- dl-cpu (macOS-10.15, 3.7, minimal)
```
and leave only `dl-cpu (ubuntu-20.04, 3.6, minimal)`?

All our tests should work under 15mins, so 40+ mins runs are just CI freezing errors :(

**Comment by Scitator** [comment]
Sorry, but you have to keep the matrix and use `exclude:` in this case ;)

**Comment by Scitator** [comment]
We still need all other test in all other scenarios

**Comment by Atharva-Phatak** [comment]
> We still need all other test in all other scenarios

Okay I will correct the mistakes.

**Comment by Scitator** [comment]
could you please return all the check, but exclude only
```
- dl-cpu (ubuntu-18.04, 3.6, minimal)
- dl-cpu (ubuntu-18.04, 3.7, minimal)
- dl-cpu (ubuntu-18.04, 3.8, minimal)
- dl-cpu (ubuntu-20.04, 3.7, minimal)
- dl-cpu (ubuntu-20.04, 3.8, minimal)
- dl-cpu (macOS-10.15, 3.7, minimal)
``` 
?
That requires you to write a precise exclude filter for 3 fields, rather than only 2 right now.

**Comment by Atharva-Phatak** [comment]
@Scitator I have made the changes, please check, if there are any please let me know

**Pull request merged**
