### PR TITLE
device fix

### PR DESCRIPTION
**Pull request by Scitator**
## Before submitting

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md), Pull Request section?
- [ ] Did you check the code style? `catalyst-make-codestyle && catalyst-check-codestyle` (`pip install -U catalyst-codestyle`).
- [ ] Did you make sure to update the docs? We use Google format for all the methods and classes.
- [ ] Did you check the docs with `make check-docs`?
- [ ] Did you write any new necessary tests?
- [ ] If you made a notable change (that affects users), did you update the [CHANGELOG](https://github.com/catalyst-team/catalyst/CHANGELOG.md)?

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

**You can use 'Login as guest' to see Teamcity build logs.**

### CODE REVIEW

**Comment by Scitator** [comment]
fix for https://github.com/catalyst-team/catalyst/issues/798

**Comment by yhn112** [comment]
In fact, I have not checked it yet, will do it a few minutes later. 
But I just have to remind that in the issue, I also mentioned problems with passing `cpu` as a device. This PR does not seem to be solving it. =)

**Comment by Scitator** [comment]
@yhn112 nice catch, updated :)

**Comment by yhn112** [comment]
Fine, it works (at least for me) now, thanks!
Sorry, there is still a small issue, because it is stated that `device: Union[str, torch.device]`, but now it works only with `torch.device`.

**Pull request merged**
