### PR TITLE
Addressing #638 to fix the MulticlassDiceMetricCallback (WIP)

### PR DESCRIPTION
**Pull request by jchen42703**
## Description
* `MulticlassDiceMetricCallback` bug fix
* Also, added `MulticlassDiceMetricCallback` to the `__init__.py` for `dl.callbacks` instead of just `callbacks.metrics`
* Removed unused arguments (`class_prefix`)
* Also, added documentation

## Related Issue
#638 
## Type of Change

- [x] Examples / docs / tutorials / contributors update
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the [Code of Conduct](https://github.com/catalyst-team/catalyst/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I have read the [Contributing](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md) guide.
- [x] I have read I need to click 'Login as guest' to see Teamcity build logs
- [x] I have checked the code-style using `make check-codestyle`.
- [x] I have written the docstring in Google format for all the methods and classes that I used.
- [ ] I have checked the docs using `make check-docs`.

### CODE REVIEW

**Comment by jchen42703** [comment]
When `class_names` is None, it works. Still need to test when `class_names` is a dictioanry.

**Comment by Scitator** [comment]
Dear @jchen42703 could you please check the codestyle and recommit with this changes?

**Comment by jchen42703** [comment]
@Scitator I still need to double check the validity of my assumption that `calculate_dice` produces class-wise dice coefficients. I'm fairly certain I'm right, but not 100% sure. I've also tested the `class_names` as a dictionary argument. I'll get to everything hopefully tomorrow night.

**Comment by jchen42703** [comment]
I'll upload some example test notebooks tomorrow (and need to sort imports)

**Comment by jchen42703** [comment]
Tests:
- [x] Multi-class classification tests
* [Notebook](https://colab.research.google.com/drive/1BZG-S9rkz2m1zHWCe3GOSNUqPQVyIX60)
* logs
  * [`class_names=None`](https://drive.google.com/open?id=1Yt8Uzf-ewpVdSQQzWLUqKhRdgxR0oMNz)
  * [`class_names={0: "artist1", 1: "artist2"}`](https://drive.google.com/open?id=19gdQTdJPGZFawoSYtJz_cRDPVHDpinAY)
    * Omitting 43 classes
    * [now averaging only the classes specified in `class_names`](https://drive.google.com/open?id=1uecAzwO7LbqqxzX8FB5XasJMdpoW3YNM)

- [x] Multi-class segmentation
  * [`class_names=None`](https://drive.google.com/open?id=1v2j4JIajiRdWstCnkM2sbmZvn5p3kILv)
  * [`class_names={1: "kidney", 2: "tumor"}`](https://drive.google.com/open?id=1BaQ7O4i-MO3bHcPX1lH7lYC3oHdfqLzf)
    * [now averaging only the classes specified in `class_names`](https://drive.google.com/open?id=1NztuW838RS9WD2_2jW2_gUrZoZGpeyL_)

**Comment by jchen42703** [comment]
Side note: Probably should average only the keys in `class_names` instead of the overall dice score for all classes so that the ignore class indices functionality is actually useful

**Comment by Scitator** [comment]
@jchen42703 could you please merge with current master? we have several tests update

**Comment by jchen42703** [comment]
I'm gonna run the tests again with the new changes real quick
Edit: worked well

**Review by Scitator — APPROVED** [review]

**Comment by Scitator** [comment]
merged 🎉 
@jchen42703 Thanks for your pull request!

**Pull request merged**
