### PR TITLE
Additive margin softmax

### PR DESCRIPTION
**Pull request by Atharva-Phatak**
## Before submitting (checklist)

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)?
- [x] Did you check the code style? `catalyst-make-codestyle && catalyst-check-codestyle` (`pip install -U catalyst-codestyle`).
- [x] Did you make sure to update the docs? We use Google format for all the methods and classes.
- [] Did you check the docs with `make check-docs`?
- [x] Did you write any new necessary tests?
- [x] Did you check that your code passes the unit tests `pytest .` ? 
- [x] Did you add your new functionality to the docs?
- [x] Did you update the [CHANGELOG](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md)?

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

PS
- [x] I know, that I could [join slack](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for pull request discussion.

### CODE REVIEW

**Comment by Atharva-Phatak** [comment]
@Scitator seems like one CI test is stopping for some reason. Observed the same with other pull requests as well.

**Comment by Scitator** [comment]
Could you please try to remove these lines? https://github.com/catalyst-team/catalyst/blob/master/.github/workflows/dl_cpu.yml#L26#L30
Few extra tests should run in this case.

**Comment by Atharva-Phatak** [comment]
> Could you please try to remove these lines? https://github.com/catalyst-team/catalyst/blob/master/.github/workflows/dl_cpu.yml#L26#L30
> Few extra tests should run in this case.

Should I create a new PR ? or commit directly to master ?

**Comment by Atharva-Phatak** [comment]
> Could you please try to remove these lines? https://github.com/catalyst-team/catalyst/blob/master/.github/workflows/dl_cpu.yml#L26#L30
> Few extra tests should run in this case.

Should I create a new PR for this ?

**Pull request merged**
