### PR TITLE
Switch from pip to poetry

### PR DESCRIPTION
**Pull request by Nimrais**
### Pull Request FAQ
- [documentation](https://catalyst-team.github.io/catalyst/)
- [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)
- [minimal examples section](https://github.com/catalyst-team/catalyst#minimal-examples)
- [changelog](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md) for main framework updates
- [Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### Checklist
- [ ] Have you updated tests for the new functionality?
- [ ] Have you added your new classes/functions to the docs?
- [ ] Have you updated the [CHANGELOG](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md)?
- [ ] Have you run [colab minimal CI/CD](https://colab.research.google.com/github/catalyst-team/catalyst/blob/master/examples/notebooks/colab_ci_cd.ipynb) with `latest` and `minimal` requirements?
- [ ] Have you checked XLA integration with [single](https://colab.research.google.com/github/catalyst-team/catalyst/blob/master/examples/notebooks/Catalyst_XLA_single_process.ipynb) and [multiple](https://colab.research.google.com/github/catalyst-team/catalyst/blob/master/examples/notebooks/Catalyst_XLA_multi_process.ipynb) processes?

### CODE REVIEW

**Comment by bagxi** [comment]
Hi @Nimrais ,
Could you please fill me in if Poetry supports [`entry_points`](https://github.com/catalyst-team/catalyst/blob/master/setup.py#L96+L101) and [`scripts`](https://github.com/catalyst-team/catalyst/blob/master/setup.py#L102+L107)? I guess it will be hard to switch to poetry without those features:(

**Comment by Nimrais** [comment]
> Hi @Nimrais ,
> Could you please fill me in if Poetry supports [`entry_points`](https://github.com/catalyst-team/catalyst/blob/master/setup.py#L96+L101) and [`scripts`](https://github.com/catalyst-team/catalyst/blob/master/setup.py#L102+L107)? I guess it will be hard to switch to poetry without those features:(

Yes, poetry has [scripts](https://python-poetry.org/docs/pyproject/#scripts).
And I think no problems with [entry points ](https://python-poetry.org/docs/pyproject/#plugins) as well.

**Comment by bagxi** [comment]
I guess by [`scripts`](https://python-poetry.org/docs/pyproject/#scripts) they mean Python scripts. But in Catalyst, we also have a bunch of bash scripts, and last time I checked (in September) there was no easy way to add bash scripts to the package.

**Comment by Nimrais** [comment]
> I guess by [`scripts`](https://python-poetry.org/docs/pyproject/#scripts) they mean Python scripts. But in Catalyst, we also have a bunch of bash scripts, and last time I checked (in September) there was no easy way to add bash scripts to the package.



> I guess by [`scripts`](https://python-poetry.org/docs/pyproject/#scripts) they mean Python scripts. But in Catalyst, we also have a bunch of bash scripts, and last time I checked (in September) there was no easy way to add bash scripts to the package.

I think no. Yeah, adding a bash script with poetry is a bit complicated. 
But it's possible. I will test it and will return it to you. 

Also, several poetry plugins can do this work for us. 
For example, https://pypi.org/project/poethepoet/.

You can define a task with it (it can be almost everything):
```
[tool.poe.tasks]
hellow-task = {"shell" = "echo 'Hellow world'"}
```
And execute it:
```
poe hellow-task
```

**Comment by bagxi** [comment]
Could you please test it?
I hope there are some ways to do it without forcing users to install Poetry. Just `pip install catalyst` + `catalyst-dl run ...`

**Comment by Nimrais** [comment]
> Could you please test it?
> I hope there are some ways to do it without forcing users to install Poetry. Just `pip install catalyst` + `catalyst-dl run ...`

Yes, adding bash script into a poetry project is possible but it can be accessed only with `poetry run <command>` from the best of my understanding.

I think this use way (`<command>`) is possible only if a script is written in python (e.g. we can wrap all our scripts with python: we have only 4).
So if you have smt like that:
```
├── cli_scripts
│   ├── __init__.py
│   ├── location.py
```
And a function `hellow` inside `location.py`

`pyproject.toml:`
```
[tool.poetry.scripts]
hellow = "cli_scripts.location:hellow"
```

After installation of the project with pip you will obtain `hellow` in your command line:
```
(cli-scripts-9hiUP3k7-py3.8) mykola@catalyst:~/cli_scripts$ hellow
hi
```

**Comment by bagxi** [comment]
Great, thank you)

And I think it is time to summon ༼ つ ◕_◕ ༽つ @Scitator ༼ つ ◕_◕ ༽つ

**Comment by Scitator** [comment]
Our current 4 bash scripts are not well documented and mostly used for contribs purposes, so I don't think it would be too pity to delist them for a while... + you still could copy-paste them if they are truly needed - we have a license in them ;)

**Pull request closed without merging**
