### PR TITLE
Added-Gem-pooling

### PR DESCRIPTION
**Pull request by Atharva-Phatak**
## Before submitting (checklist)

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)?
- [x] Did you check the code style? `catalyst-make-codestyle && catalyst-check-codestyle` (`pip install -U catalyst-codestyle`).
- [x] Did you make sure to update the docs? We use Google format for all the methods and classes.
- [x] Did you check the docs with `make check-docs`?
- [x] Did you write any new necessary tests?
- [x] Did you check that your code passes the unit tests `pytest .` ? 
- [x] Did you add your new functionality to the docs?
- [x] Did you update the [CHANGELOG](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md)?

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

PS
- [x] I know, that I could [join slack](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for pull request discussion.

### CODE REVIEW

**Comment by Atharva-Phatak** [comment]
@Scitator some help please ?

**Comment by Scitator** [comment]
@Atharva-Phatak could you please add a readme file for https://github.com/catalyst-team/catalyst/pull/1120?
to reduce git diff mergind... I have just copy-paste your main methods for the new PR

**Comment by Scitator** [comment]
we should update the contribution guide soon enough

**Comment by Scitator** [comment]
I have also added you to github "outside contributions", so you should have write access to the project

**Comment by Atharva-Phatak** [comment]
> we should update the contribution guide soon enough

Yeah that would be amazing I am just having problems with codestyle, everything else is super amazing in catalyst

**Comment by Atharva-Phatak** [comment]
> @Atharva-Phatak could you please add a readme file for #1120?
> to reduce git diff mergind... I have just copy-paste your main methods for the new PR

Do you want me to add the contribution guide readme ?

**Comment by Scitator** [comment]
> Do you want me to add the contribution guide readme ?

If you could do so, that would be great! We already have one - https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md#contribution-guide, but if could be done better, I think :)

**Comment by Scitator** [comment]
speaking of the https://github.com/catalyst-team/catalyst/pull/1120, could you please add a readme to the https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md, so we could finally merge your contribution?)
All checks have passed.

**Comment by Atharva-Phatak** [comment]
> speaking of the #1120, could you please add a readme to the https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md, so we could finally merge your contribution?)
> All checks have passed.

@Scitator I would need create new PR for it since I cant directly contribute to master. So if its okay I can create a new PR having changes mentioned in CHANGELOG.md.

**Pull request closed without merging**
