### PR TITLE
Change layerwise to layerwise_params

### PR DESCRIPTION
**Pull request by MrNightSky**
## Before submitting (checklist)

- [ ] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)?
- [ ] Did you check the code style? `catalyst-make-codestyle && catalyst-check-codestyle` (`pip install -U catalyst-codestyle`).
- [ ] Did you make sure to update the docs? We use Google format for all the methods and classes.
- [ ] Did you check the docs with `make check-docs`?
- [ ] Did you write any new necessary tests?
- [ ] Did you check that your code passes the unit tests `pytest .` ? 
- [ ] Did you add your new functionality to the docs?
- [ ] Did you update the [CHANGELOG](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md)?
- [ ] Did you run [colab minimal CI/CD](https://colab.research.google.com/drive/1JCGTVvWlrIsLXMPRRRSWiAstSLic4nbA) with `latest` and `minimal` requirements?

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### FAQ
Please review the FAQ before submitting an issue:
- [ ] I have read the [documentation and FAQ](https://catalyst-team.github.io/catalyst/)
- [ ] I have reviewed the [minimal examples section](https://github.com/catalyst-team/catalyst#minimal-examples)
- [ ] I have checked the [changelog](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md) for main framework updates
- [ ] I have read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)
- [ ] I have joined [Catalyst slack (#__questions channel)](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw) for issue discussion

### CODE REVIEW

**Comment by Scitator** [comment]
overall... nice catch! good to see such a documentation bug found
nevertheless, @bagxi @Ditwoo, what do you think about naming? `layerwise_params` or simple `layerwise`?
@MrNightSky from the usage perspective, what is more clear?

**Review by Scitator — APPROVED** [review]

**Comment by MrNightSky** [comment]
I think layerwise_params better for dict parameter than layerwise.

What's wrong with my PR? Why it not go through the test? I have not changed any code, and my changes was only at examples config, that I thought not used anywhere.

**Comment by Scitator** [comment]
That's Github CI robustness issue :)

**Review by ditwoo — APPROVED** [review]

**Comment by Scitator** [comment]
could you please add the PR to the [Changelog](https://github.com/catalyst-team/catalyst/blob/master/CHANGELOG.md)?

**Comment by MrNightSky** [comment]
Ok
I can add PR to Changelog. But I do it first time. Where to add this info? Like this?

[YY.MM.R] - YYYY-MM-DD
Added
example how to add extra params to DataLoader in config files
Changed
layerwise to correct key value layerwise_params in config files
Removed
Fixed
customizing what happens in train() notebook (#1203)

**Comment by Scitator** [comment]
fixed :)
you have fixed the docs, I think, just to notice the change

**Comment by MrNightSky** [comment]
Done, but by another PR https://github.com/catalyst-team/catalyst/pull/1216

**Pull request merged**
