### PR TITLE
Add VisdomLogger, VisdomRunner, SupervisedVisdomRunner

### PR DESCRIPTION
**Pull request by Entodi**
## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the [Code of Conduct](https://github.com/catalyst-team/catalyst/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I have read the [Contributing](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md) guide.
- [x] I have checked the code-style using `make check-codestyle`.
- [ ] I have written tests for all new methods and classes that I created.
- [ ] I have written the docstring in Google format for all the methods and classes that I used.
- [ ] I have checked the docs using `make check-docs`.
- [ ] I have read I need to click 'Login as guest' to see Teamcity build logs.

### CODE REVIEW

**Comment by Scitator** [comment]
Dear @Entodi, thanks for you PR.
Could you please contribute VisdomLogger instead? LIke an [Alchemy](https://github.com/catalyst-team/catalyst/blob/master/catalyst/contrib/dl/callbacks/alchemy.py) one.  All external runners should be removed in 20.04 release :)

**Comment by Entodi** [comment]
@Scitator Will do

**Comment by Scitator** [comment]
just to be sure, you don't need to implement alchecmy.Logger, only AlchemyLogger (callback version)

**Comment by Scitator** [comment]
@Entodi could you please merge with master?
we have updated tests.

**Comment by Entodi** [comment]
I will start a new pull request since there is 20.3.

**Pull request closed without merging**
