### PR TITLE
Metric Learning tutorial

### PR DESCRIPTION
**Pull request by smivv**
## Description

Metric learning tutorial.

## Related Issue

https://github.com/catalyst-team/catalyst/issues/459

## Type of Change

- [x] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the [Code of Conduct](https://github.com/catalyst-team/catalyst/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I have read the [Contributing](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md) guide.
- [x] I have read I need to click 'Login as guest' to see Teamcity build logs
- [x] I have checked the code-style using `make check-codestyle`.
- [x] I have written the docstring in Google format for all the methods and classes that I used.
- [x] I have checked the docs using `make check-docs`.

### CODE REVIEW

**Comment by Scitator** [comment]
@smivv Could you please add some PR description, what are the main features of new tutorial?

**Comment by Scitator** [comment]
@smivv just to be sure, I mean to write the description to this PR with main points of the proposed tutorial and what have been done.

**Comment by smivv** [comment]
@Scitator, honestly speaking nothing very specific, just took your classification tutorial, changed last FC layer of the network and set it up on training with triplet loss and knnmetriccallback :)

**Comment by Scitator** [comment]
let's make something bigger, with advanced metric learning techniques for future tutorial.

**Comment by Scitator** [comment]
Let's talk more about pure metric learning tutorial. For now, I would like to close this PR.

**Pull request closed without merging**
