### PR TITLE
Fixed  OneCycleLRWithWarmup

### PR DESCRIPTION
**Pull request by lokeshkvn**
## Before submitting

- [x] Was this discussed/approved via a Github issue? (no need for typos and docs improvements)
- [x] Did you read the [contribution guide](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md)?
- [x] Did you check the code style? `catalyst-make-codestyle && catalyst-check-codestyle` (`pip install -U catalyst-codestyle`).
_Not able to check its showing _**'catalyst-make-codestyle' is not recognized as an internal or external command**_ Please suggest me how to do this. I am in Windows 10 environment_
- [ ] Did you make sure to update the docs? We use Google format for all the methods and classes.
- [x] Did you check the docs with `make check-docs`?
- [x] Did you write any new necessary tests?
- [ ] Did you add your new functionality to the docs?
- [x] Did you update the [CHANGELOG](https://github.com/catalyst-team/catalyst/CHANGELOG.md)?
- [x] **You can use 'Login as guest' to see Teamcity build logs.**

## Description

OneCycleLRWithWarmup starts ahead of initial LR (does not start with init_lr)

## Related Issue

https://github.com/catalyst-team/catalyst/issues/851

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in Github issues there's a high chance it will not be merged.

### CODE REVIEW

**Comment by Scitator** [comment]
Dear @lokeshkvn,
Thank you for you contribution!
Nevertheless, what do you think about adding a few tests on this feature to ensure that all future users will be satisfied with it? I think, we could simply add learning rate check during some test pipeline. What do you think about it?

**Comment by lokeshkvn** [comment]
@Scitator Welcome! 
Yes, One simple check for the initial learning rate will be good. I will be adding tests to it soon to the pipelines.

**Comment by Scitator** [comment]
@lokeshkvn 
Huge thanks to you. If you need any examples for tests writing, here are good examples:
- https://github.com/catalyst-team/catalyst/pull/858
- https://github.com/catalyst-team/catalyst/pull/855

And don't hesitate to ask questions if you need. You could also join our slack to speak with the team easily https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw

**Comment by lokeshkvn** [comment]
Thank you @Scitator . I will check this out for writing test cases. 👍

**Comment by Scitator** [comment]
@lokeshkvn 
How are you doing? We are going to make a new release this week, would you like to take part in it?

**Comment by lokeshkvn** [comment]
> @lokeshkvn
> How are you doing? We are going to make a new release this week, would you like to take part in it?

Hi @Scitator I am working on the tight schedule. I would love to submit the test case soon. Thanks I will try to make it.

**Comment by lokeshkvn** [comment]
@Scitator
Let me know if any changes required  👍

**Review by Scitator — DISMISSED** [review]

**Comment by Scitator** [comment]
Dear @lokeshkvn there are some issues with catalyst-cv tests. I can't merge until they pass.

**Comment by lokeshkvn** [comment]
@Scitator Thanks for the update. If I can help please let me know.

**Pull request merged**
