### PR TITLE
#192 [devops] Move dependencies to PipEnv

### PR DESCRIPTION
**Pull request by andrey-avdeev**
Pipfile and Pipfile.lock were added

### CODE REVIEW

**Comment by Scitator** [comment]
Hi, could you please add more info about how to use this feature properly?

**Comment by andrey-avdeev** [comment]
# First step:
1. Install [Pipenv](https://github.com/pypa/pipenv)
2. Clone & open this repository in PyCharm Professional IDE.
3. Install plugins for pipenv support 
4. Right mouse click on Pipfile and choose "Synchronize 'Pipfile'"
All dependencies with hash sums and required Python version will be synchronized with your project
# Production and dev|test packages
For production usage:
`pipenv install numpy`
For dev|test usage:
`pipenv install numpy --dev`
# CI/CD optimization
Add this commands to the top of your Dockerfile as higher as posible:

RUN pip install pipenv

ADD Pipfile /Pipfile
ADD Pipfile.lock /Pipfile.lock

WORKDIR /

RUN pipenv install --system --deploy

# Security
You will get an error while CI build phase, if any python package was removed or replaced by invalid package in pypi registry.

Additional references: 
- [PyCharm support](https://www.jetbrains.com/help/pycharm/pipenv.html)

**Comment by maruschin** [comment]
Why pipenv?
I think [poetry](https://poetry.eustace.io/) is better choice.
It's better suitable for packaging and dependence management.
Pipenv deliver only dependence management, but it's awful:
* [Pipenv: promises a lot, delivers very little](https://chriswarrick.com/blog/2018/07/17/pipenv-promises-a-lot-delivers-very-little/)

**Comment by Scitator** [comment]
Hi, 
as @maruschin correctly mentioned – poetry is better choice (after some my personal investigation in the filed of python deps managers)

**Pull request closed without merging**
