### PR TITLE
Add classwise iou callback

### PR DESCRIPTION
**Pull request by ai-niki**
## Description

Add classwise IoU callback and remove MulticlassIOUMetricCallback which didn't work.

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have read the [Code of Conduct](https://github.com/catalyst-team/catalyst/blob/master/CODE_OF_CONDUCT.md) document.
- [ ] I have read the [Contributing](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md) guide.
- [x] I have checked the code-style using `make check-style`.
- [ ] I have written the docstring in Google format for all the methods and classes that I used.
- [ ] I have checked the docs using `make check-docs`.

### CODE REVIEW

**Comment by Scitator** [comment]
Hi @pokidyshev ,
The PR looks really cool! Nevertheless, could you please add some tests to check,
- IOU metric functionality
- Multi-Class IOU metric functionality
- IOU Callback 
- Multi-Class IOU Callback  

It's much easier, than it looks :)
For an example you can check out tests for precision/recall/f1 metrics
https://github.com/catalyst-team/catalyst/blob/master/catalyst/dl/tests/test_ppv_tpr_f1.py

**Comment by Scitator** [comment]
Dear @bagxi could you please check @pokidyshev PR (and maybe tests?) and uncheck [WIP] label after that?

**Comment by ai-niki** [comment]
Ok, @Scitator, here you are! Tests are ready.

**Comment by ai-niki** [comment]
However, I didn't find any examples on callback-tests so I won't implement them.

**Review by bagxi — APPROVED** [review]

**Comment by smivv** [comment]
Already tried that PR - does not work.

**Comment by ai-niki** [comment]
@smivv Could you please provide more info? It works like this:
```
    iou_cw:
      callback: ClasswiseIouCallback
      prefix: iou
      threshold: 0.5
      classes: [ "cl1", "cl2", "cl3", "cl4" ]
```

**Comment by smivv** [comment]
@pokidyshev, The main issue in my case is that [here](https://github.com/catalyst-team/catalyst/blob/011b43e64aa59d5e91f4b1e8e1c7fc13f8a58557/catalyst/dl/utils/criterion/iou.py#L36) we have some channels, while I have only [B, H, W] dimensions in targets.

**Comment by ai-niki** [comment]
So you have only one class and background?

**Comment by smivv** [comment]
I encode them as [0, 1, 2, ...] in one channel target.

**Comment by ai-niki** [comment]
In that case the 'iou()' method wouldn’t have worked anyway even before the PR. It works great for multilabel segmentation setup, when you have channels, so the PR is fine. Feel free to update the method for the multiclass case :)

**Pull request merged**
