### PR TITLE
Update supervised.py

### PR DESCRIPTION
**Pull request by SindhuVenna**
To make resume training work as expected when callbacks is a list and not an ordered dict

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have read the [Code of Conduct](https://github.com/catalyst-team/catalyst/blob/master/CODE_OF_CONDUCT.md) document.
- [x] I have read the [Contributing](https://github.com/catalyst-team/catalyst/blob/master/CONTRIBUTING.md) guide.
- [x] I have checked the code-style using `make check-style`.
- [x] I have written the docstring in Google format for all the methods and classes that I used.
- [x] I have checked the docs using `make check-docs`.

### CODE REVIEW

**Comment by TezRomacH** [comment]
Hi! Did you check that this change really helps?

At first glance, it doesn't seem like it's going to have any effect. The experiment is initialized in the code.
```
experiment = self._default_experiment( 
            stage="train", 
            model=model, 
            loaders=loaders, 
            callbacks=callbacks,
...
```

And within SupervisedExperiment there is also `self._callbacks = process_callbacks(callbacks)`.

**Comment by TezRomacH** [comment]
Also, could you please run the command `isort -rc --settings-path ./setup.cfg` to sort your imports correctly? :)

**Comment by SindhuVenna** [comment]
> Hi! Did you check that this change really helps?
> 
> At first glance, it doesn't seem like it's going to have any effect. The experiment is initialized in the code.
> 
> ```
> experiment = self._default_experiment( 
>             stage="train", 
>             model=model, 
>             loaders=loaders, 
>             callbacks=callbacks,
> ...
> ```
> 
> And within SupervisedExperiment there is also `self._callbacks = process_callbacks(callbacks)`.

Hi , It helped me to resume training which I wasn't able to before

**Comment by lightforever** [comment]
@TezRomacH , How do you do?

This code in SupervisedRunner does not process a list of callbacks correctly:

```
            callbacks = callbacks or OrderedDict()
            checkpoint_callback_flag = any([
                isinstance(x, CheckpointCallback)
                for x in callbacks.values()
            ])
            if not checkpoint_callback_flag:
                callbacks["loader"] = CheckpointCallback(resume=resume)
            else:
                raise NotImplementedError("CheckpointCallback already exist")

```

Therefore, I agree with @SindhuVenna.

@SindhuVenna , could you please:

1. Fix the import order in the module? There is a convention to place more fundamental libraries higher. The previous order was correct.

2. Remove the import: 'from catalyst.dl.utils import callbacks'. You don't need this import in the code. Do you?

3. Resolve conflicts with the main branch.

Thank you!

**Review by lightforever — APPROVED** [review]

**Comment by lightforever** [comment]
Pardon for such weird actions. I faced a bug in github: when Travis pulls from this pull request, the HEAD is not correct.

I am trying to create a new pull request to fix this issue.

**Comment by lightforever** [comment]
@SindhuVenna , there is a strange situation with our CI system. Could you copy all files from this branch to a new branch and create a new pull request?

**Comment by Scitator** [comment]
@SindhuVenna  could you please merge with master? we have fixed the CI tests issue

**Review by lightforever — APPROVED** [review]

**Review by TezRomacH — COMMENTED** [review]
How did the tests go before without these indents?

Perhaps now, with fixed dependencies, it is time to restart the build.

**Comment by lightforever** [comment]
Build succeeded after fixed dependencies were merged. You may restart the build on Travis: https://travis-ci.com/catalyst-team/catalyst/builds/139286101

**Comment by Scitator** [comment]
could you please remove all unnecessary diff with tabs? I am ready to merge, but could not see the main point for this PR 😂

**Pull request merged**
