### PR TITLE
Fixed OptimizerCallback call before CriterionCallback

### PR DESCRIPTION
**Pull request by Dipet**
Code for reproduce:
```
import torch
from torch import nn
from torch.optim import Adam
from torch.utils.data import Dataset, DataLoader
from torchvision.models import mobilenet_v2

import catalyst
from catalyst.dl import SupervisedRunner, OptimizerCallback

print(torch.__version__)
print(catalyst.__version__)


class _Dataset(Dataset):
    def __len__(self):
        return 1

    def __getitem__(self, item):
        return {'features': torch.rand((3, 256, 1600)), 'targets': torch.Tensor([0])}


dataloader = DataLoader(_Dataset())

model = mobilenet_v2(False, num_classes=1)
runner = SupervisedRunner()
optim = Adam(model.parameters())
runner.train(model, nn.BCEWithLogitsLoss(), optim, {'train': dataloader, 'valid': dataloader}, 'test',
             callbacks=[OptimizerCallback(accumulation_steps=2)]
             )

```

Output:
```
1.2.0
19.08.7
Traceback (most recent call last):
    callbacks=[OptimizerCallback(accumulation_steps=2)]
  File "/mnt/HDD/home/druzhinin/GitRepos/catalyst/catalyst/dl/runner/supervised.py", line 131, in train
    self.run_experiment(experiment, check=check)
  File "/mnt/HDD/home/druzhinin/GitRepos/catalyst/catalyst/dl/core/runner.py", line 196, in run_experiment
    self._run_event("exception")
  File "/mnt/HDD/home/druzhinin/GitRepos/catalyst/catalyst/dl/core/runner.py", line 96, in _run_event
    getattr(self.state, f"on_{event}_post")()
  File "/mnt/HDD/home/druzhinin/GitRepos/catalyst/catalyst/dl/core/state.py", line 173, in on_exception_post
    logger.on_exception(self)
  File "/mnt/HDD/home/druzhinin/GitRepos/catalyst/catalyst/dl/callbacks/logging.py", line 189, in on_exception
    raise exception
  File "/mnt/HDD/home/druzhinin/GitRepos/catalyst/catalyst/dl/core/runner.py", line 193, in run_experiment
    self._run_stage(stage)
  File "/mnt/HDD/home/druzhinin/GitRepos/catalyst/catalyst/dl/core/runner.py", line 175, in _run_stage
    self._run_epoch(loaders)
  File "/mnt/HDD/home/druzhinin/GitRepos/catalyst/catalyst/dl/core/runner.py", line 162, in _run_epoch
    self._run_loader(loader)
  File "/mnt/HDD/home/druzhinin/GitRepos/catalyst/catalyst/dl/core/runner.py", line 131, in _run_loader
    self._run_batch(batch)
  File "/mnt/HDD/home/druzhinin/GitRepos/catalyst/catalyst/dl/core/runner.py", line 113, in _run_batch
    self._run_event("batch_end")
  File "/mnt/HDD/home/druzhinin/GitRepos/catalyst/catalyst/dl/core/runner.py", line 93, in _run_event
    getattr(callback, f"on_{event}")(self.state)
  File "/mnt/HDD/home/druzhinin/GitRepos/catalyst/catalyst/dl/callbacks/optimizer.py", line 111, in on_batch_end
    loss.backward()
AttributeError: 'NoneType' object has no attribute 'backward'
```

### CODE REVIEW

**Comment by Scitator** [comment]
Hi,

Thanks for the PR, nevertheless, I think it is much more appropriate to resolve callbacks order through some `priority`/`order` flag.

**Comment by i-zaitsev** [comment]
@Dipet @Scitator if you think that someone could help to make this more generic, I can make a try if needed.

**Comment by Dipet** [comment]
@devforfu If you can try do it. My code wrong, i forget add non standard callbacks to list.

**Comment by i-zaitsev** [comment]
For future reference, the authors opened PR #343 to address the issue.

**Pull request closed without merging**
